# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-16 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(default='Awesome workout EDM'),
            preserve_default=False,
        ),
    ]
