# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-16 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_artist_songs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='last_name',
        ),
    ]
